# -*- coding: utf-8 -*-
"""Copy of Polynomial Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-W3ePNDUyJmr3aLl6eP7YXjkD4RWma2
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

# Dataset
X = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)
Y = np.array([2,5,10,17,26,37,50,65,82,101])

# Polynomial Features
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)

# Train Model
model = LinearRegression()
model.fit(X_poly, Y)

# Prediction
Y_pred = model.predict(X_poly)

# Plot
plt.scatter(X, Y)
plt.plot(X, Y_pred)
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Polynomial Regression")
plt.show()

# Prediction for new value
new_x = poly.transform([[11]])
print("Prediction for x=11 :", model.predict(new_x))